language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.5-dev
  - nightly
  - pypy
install:
  - make install-dev
  - pip install coveralls
script:
  - make clean doc test
after_success:
  - coveralls
